# -*- coding: utf-8 -*-
"""Spelling correction using jaccard similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUkkig5TC9BIabtDkAN7FV9wsYoUAHjN
"""

# correct word
dictionary= ["receive","believe","friend","learning"]

print(dictionary)
['receive','believe','friend','learning']

def char_ngrams(word, n=2):
  ngrams = []
  for i in range(len(word) - n + 1):
    ngrams.append(word[i:i+n])
  return set(ngrams)

#jaccard similar function
def jaccard_similarity(a,b):
  set1=set(a)
  set2=set(b)
  return len(set1 & set2)/len(set1|set2)

def correct_spelling(word,dictionary,n=2):
  word_ngrams = char_ngrams(word,n)
  best_match=None
  best_score = -1 # Initialize with a score that can be easily beaten

  for correct_word in dictionary:
    correct_ngrams = char_ngrams(correct_word, n)
    score = jaccard_similarity(word_ngrams , correct_ngrams)

    if score > best_score:
      best_score = score
      best_match = correct_word

  return best_match ,best_score

wrong_words_list = ["recieve","believe","frien","learnig"]
for w in wrong_words_list:
  match,score = correct_spelling(w,dictionary)
  print(f"{w}--->{match} (score:{score:.2f})")



"""##

improved
"""

import re

def preprosessing(word):
  word=word.lower()
  word=re.sub(r'[^a-z]',"",word)
  return word

preprosessing("hello123!")

def correct_spelling(word,dictionary,n=2):
  word = preprosessing(word)
  word_ngrams = char_ngrams(word,n)
  best_match=None
  best_score = -1 # Initialize with a score that can be easily beaten

  for correct_word in dictionary:
    correct_ngrams = char_ngrams(correct_word, n)
    score = jaccard_similarity(word_ngrams , correct_ngrams)

    if score > best_score:
      best_score = score
      best_match = correct_word

  return best_match ,best_score

dictionary.append("building")

test_word=["recieve","3freind","beliv2",]
for w in wrong_words_list:
  match,score = correct_spelling(w,dictionary)
  print(f"{w}--->{match} (score:{score:.2f})")

"""user input version

"""

user_word = input("enter a word")
match,score = correct_spelling(user_word,dictionary)
print(f"suggested correction--->{match} (score:{score:.2f})")